# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'IATAblumareks' do
    pod 'BMSCore', '~> 2.0'

  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "SwiftSpinner", '~> 1.3.0'
  pod "JSQMessagesViewController", '~> 7.3.4'

  # Pods for IATAblumareks

  target 'IATAblumareksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IATAblumareksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
